name: a_pos_flutter
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  # Dialogs and Alerts
  awesome_dialog: ^3.2.1

  # Connectivity and Networking
  connectivity_plus: ^6.0.3
  dio: ^5.5.0+1

  # Core module
  core:
    path: modules/core

  # Utilities
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  envied: ^0.5.4+1
  # logger: ^2.3.0
  fpdart: ^1.1.0
  uuid: ^4.4.2

  # Service locator
  get_it: ^7.7.0

  # Local cache
  shared_preferences: ^2.2.3

  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6

  # UI
  flutter_colorpicker: ^1.1.0
  flutter_screenutil: ^5.9.3
  cupertino_icons: ^1.0.6

  # Localization
  easy_localization: ^3.0.7

  # Image and File Handling
  image_picker: ^1.1.2
  pdf: ^3.11.0
  printing: ^5.13.1

  # Window and UI Kit
  ui_kit:
    path: modules/ui_kit
  window_manager: ^0.3.9
  table_calendar: ^3.1.2

dev_dependencies:
  # Build and Generation
  build_runner: ^2.4.11
  envied_generator: ^0.5.4+1
  flutter_gen_runner: ^5.6.0

  # Linting and Testing
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

  # Icons and Launcher
  flutter_launcher_icons: ^0.13.1

  # Serialization
  json_serializable: ^6.8.0

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  image_path: "assets/icon/ic_logo.png"
  android: true
  ios: true
  remove_alpha_ios: true
  windows:
    generate: true
    image_path: "assets/icon/ic_logo.png"
    icon_size: 48

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
    - assets/images/
    - assets/images/on_boarding/
    - assets/images/tables/
    - assets/images/utility_items/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
    - family: OpenSans
      fonts:
        - asset: assets/fonts/open_sans/OpenSans-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-SemiBold.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700
