part of '../view/menu_option_view.dart';

mixin _OptionMixin on State<MenuOptionsView> {
  int? selectedOptionIndex = 0;
  int? selectedGroupIndex = 0;
  late List<Map<String, dynamic>> selectedOptionData;
  Color? selectedColor;

  //TODO: set this controller to group name
  late TextEditingController _optionGroupController;
  late TextEditingController _optionNameController;
  late TextEditingController _descriptionController;
  late TextEditingController _priceController;
  late TextEditingController _lunchPriceController;
  late TextEditingController _happyHourController;
  late TextEditingController _deliveryPriceController;
  late TextEditingController _takeOutPriceController;
  late TextEditingController _taxController;
  void setTextFieldControllerText(int index) {
    _optionNameController.text = selectedOptionData[selectedOptionIndex ?? 0]['optionName'] ?? '';
    _descriptionController.text =
        selectedOptionData[selectedOptionIndex ?? 0]['optionDescription'] ?? '';
    _priceController.text = selectedOptionData[selectedOptionIndex ?? 0]['price'].toString();
    _lunchPriceController.text = selectedOptionData[selectedOptionIndex ?? 0]['lPrice'].toString();
    _happyHourController.text = selectedOptionData[selectedOptionIndex ?? 0]['hPrice'].toString();
    _deliveryPriceController.text =
        selectedOptionData[selectedOptionIndex ?? 0]['dPrice'].toString();
    _takeOutPriceController.text =
        selectedOptionData[selectedOptionIndex ?? 0]['tPrice'].toString();
    _taxController.text = selectedOptionData[selectedOptionIndex ?? 0]['tax'].toString();
  }

  @override
  void initState() {
    super.initState();
    selectedOptionData = groupedOptionData[0];
    _optionGroupController = TextEditingController(
        text: selectedOptionData[selectedOptionIndex ?? 0]['optionName'] ?? '');
    _optionNameController = TextEditingController(
        text: selectedOptionData[selectedOptionIndex ?? 0]['optionName'] ?? '');
    _descriptionController = TextEditingController(
        text: selectedOptionData[selectedOptionIndex ?? 0]['optionDescription'] ?? '');
    _priceController = TextEditingController(
        text: selectedOptionData[selectedOptionIndex ?? 0]['price'].toString());
    _lunchPriceController = TextEditingController(
        text: selectedOptionData[selectedOptionIndex ?? 0]['lPrice'].toString());
    _happyHourController = TextEditingController(
        text: selectedOptionData[selectedOptionIndex ?? 0]['hPrice'].toString());
    _deliveryPriceController = TextEditingController(
        text: selectedOptionData[selectedOptionIndex ?? 0]['dPrice'].toString());
    _takeOutPriceController = TextEditingController(
        text: selectedOptionData[selectedOptionIndex ?? 0]['tPrice'].toString());
    _taxController =
        TextEditingController(text: selectedOptionData[selectedOptionIndex ?? 0]['tax'].toString());
  }

  void onRowTap(index) {
    setState(() {
      if (selectedOptionIndex == index) {
        return;
      } else {
        selectedOptionIndex = index;
        setTextFieldControllerText(index);
      }
    });
  }

  void onGroupTapped(index) {
    setState(() {
      if (selectedGroupIndex == index) {
        return;
      } else {
        selectedGroupIndex = index;
        selectedOptionIndex = 0;
        setTextFieldControllerText(0);
      }
    });
  }

  void onTaxCheckboxChanged(String key, bool value) {
    setState(() {
      if (selectedOptionIndex != null) {
        selectedOptionData[selectedOptionIndex!][key] = value;
      }
    });
  }

  void setSelectedOptionData(index) {
    if (index < 0 || index >= groupedOptionData.length) {
      selectedOptionData = groupedOptionData[0];
    } else {
      selectedOptionData = groupedOptionData[index];
    }
  }

  final List<List<Map<String, dynamic>>> groupedOptionData = [
    [
      {
        'optionName': 'Option 1',
        'optionDescription': 'Description 1',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 3',
        'optionDescription': 'Description 3',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 3',
        'optionDescription': 'Description 3',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 3',
        'optionDescription': 'Description 3',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 3',
        'optionDescription': 'Description 3',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 4',
        'optionDescription': 'Description 4',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 5',
        'optionDescription': 'Description 5',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
    ],
    [
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 6',
        'optionDescription': 'Description 6',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 7',
        'optionDescription': 'Description 7',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
    ],
    [
      {
        'optionName': 'Option 8',
        'optionDescription': 'Description 8',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 9',
        'optionDescription': 'Description 9',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 10',
        'optionDescription': 'Description 10',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
    ],
    [
      {
        'optionName': 'Option 11',
        'optionDescription': 'Description 11',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 12',
        'optionDescription': 'Description 12',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
    ],
    [
      {
        'optionName': 'Option 8',
        'optionDescription': 'Description 8',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 9',
        'optionDescription': 'Description 9',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
      {
        'optionName': 'Option 10',
        'optionDescription': 'Description 10',
        'price': 0.0,
        'lPrice': 0.0,
        'hPrice': 0.0,
        'dPrice': 0.0,
        'tPrice': 0.0,
        'tax': 0.0,
        'barTax': 0.0,
        'percentTax': false,
      },
    ],
  ];
}
